services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betterme-app
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
    depends_on:
      - postgis
    restart: unless-stopped

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./data:/data_in_container:ro
    restart: unless-stopped

volumes:
  postgis_data:
