services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betterme-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - postgis
    restart: unless-stopped

  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgis_data:
